<ul class="rating d-flex">
    @if(reviewAverage($product_id) == 0)
        <li class="text-danger">Not reviewed</li>
    @elseif(reviewAverage($product_id) == 1)
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star-o"></i></li>
        <li><i class="fa fa-star-o"></i></li>
        <li><i class="fa fa-star-o"></i></li>
        <li><i class="fa fa-star-o"></i></li>
    @elseif(reviewAverage($product_id) == 1.5)
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star-half-o"></i></li>
        <li><i class="fa fa-star-o"></i></li>
        <li><i class="fa fa-star-o"></i></li>
        <li><i class="fa fa-star-o"></i></li>
    @elseif(reviewAverage($product_id) == 2)
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star-o"></i></li>
        <li><i class="fa fa-star-o"></i></li>
        <li><i class="fa fa-star-o"></i></li>
    @elseif(reviewAverage($product_id) == 2.5)
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star-half-o"></i></li>
        <li><i class="fa fa-star-o"></i></li>
        <li><i class="fa fa-star-o"></i></li>
    @elseif(reviewAverage($product_id) == 3)
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star-o"></i></li>
        <li><i class="fa fa-star-o"></i></li>
    @elseif(reviewAverage($product_id) == 3.5)
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star-half-o"></i></li>
        <li><i class="fa fa-star-o"></i></li>
    @elseif(reviewAverage($product_id) == 4)
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star-o"></i></li>
    @elseif(reviewAverage($product_id) == 4.5)
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star-half-o"></i></li>
    @else(reviewAverage($product_id) == 5)
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
    @endif
</ul>